// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly sabbath: sabbath.ServiceClient
    public readonly feed: feed.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.sabbath = new sabbath.ServiceClient(base)
        this.feed = new feed.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createHymn as api_sabbath_create_hymn_createHymn } from "~backend/sabbath/create_hymn";
import { deleteBibleBookmark as api_sabbath_delete_bible_bookmark_deleteBibleBookmark } from "~backend/sabbath/delete_bible_bookmark";
import { deleteBibleVerseNote as api_sabbath_delete_bible_verse_note_deleteBibleVerseNote } from "~backend/sabbath/delete_bible_verse_note";
import { findChurches as api_sabbath_find_churches_findChurches } from "~backend/sabbath/find_churches";
import { getBibleBookmarks as api_sabbath_get_bible_bookmarks_getBibleBookmarks } from "~backend/sabbath/get_bible_bookmarks";
import { getBibleBooks as api_sabbath_get_bible_books_getBibleBooks } from "~backend/sabbath/get_bible_books";
import { getBibleChapter as api_sabbath_get_bible_chapter_getBibleChapter } from "~backend/sabbath/get_bible_chapter";
import { getBibleCommentary as api_sabbath_get_bible_commentary_getBibleCommentary } from "~backend/sabbath/get_bible_commentary";
import { getBibleCrossReferences as api_sabbath_get_bible_cross_references_getBibleCrossReferences } from "~backend/sabbath/get_bible_cross_references";
import { getBibleTranslations as api_sabbath_get_bible_translations_getBibleTranslations } from "~backend/sabbath/get_bible_translations";
import { getBibleVerse as api_sabbath_get_bible_verse_getBibleVerse } from "~backend/sabbath/get_bible_verse";
import { getBibleVerseNotes as api_sabbath_get_bible_verse_notes_getBibleVerseNotes } from "~backend/sabbath/get_bible_verse_notes";
import { getCurrentSabbathSchoolLesson as api_sabbath_get_current_sabbath_school_lesson_getCurrentSabbathSchoolLesson } from "~backend/sabbath/get_current_sabbath_school_lesson";
import { getDevotionals as api_sabbath_get_devotionals_getDevotionals } from "~backend/sabbath/get_devotionals";
import { getHymnById as api_sabbath_get_hymn_by_id_getHymnById } from "~backend/sabbath/get_hymn_by_id";
import { getHymnCategories as api_sabbath_get_hymn_categories_getHymnCategories } from "~backend/sabbath/get_hymn_categories";
import { getHymnThemes as api_sabbath_get_hymn_themes_getHymnThemes } from "~backend/sabbath/get_hymn_themes";
import { getHymns as api_sabbath_get_hymns_getHymns } from "~backend/sabbath/get_hymns";
import { getJournalEntries as api_sabbath_get_journal_entries_getJournalEntries } from "~backend/sabbath/get_journal_entries";
import { getNotificationSettings as api_sabbath_get_notification_settings_getNotificationSettings } from "~backend/sabbath/get_notification_settings";
import { getPendingNotifications as api_sabbath_get_pending_notifications_getPendingNotifications } from "~backend/sabbath/get_pending_notifications";
import { getPreferences as api_sabbath_get_preferences_getPreferences } from "~backend/sabbath/get_preferences";
import { getSabbathSchoolDailyStudies as api_sabbath_get_sabbath_school_daily_studies_getSabbathSchoolDailyStudies } from "~backend/sabbath/get_sabbath_school_daily_studies";
import { getSabbathSchoolLessons as api_sabbath_get_sabbath_school_lessons_getSabbathSchoolLessons } from "~backend/sabbath/get_sabbath_school_lessons";
import { getSabbathSchoolQuarters as api_sabbath_get_sabbath_school_quarters_getSabbathSchoolQuarters } from "~backend/sabbath/get_sabbath_school_quarters";
import { getSabbathTimes as api_sabbath_get_sabbath_times_getSabbathTimes } from "~backend/sabbath/get_sabbath_times";
import { saveBibleBookmark as api_sabbath_save_bible_bookmark_saveBibleBookmark } from "~backend/sabbath/save_bible_bookmark";
import { saveBibleVerseNote as api_sabbath_save_bible_verse_note_saveBibleVerseNote } from "~backend/sabbath/save_bible_verse_note";
import { saveJournalEntry as api_sabbath_save_journal_entry_saveJournalEntry } from "~backend/sabbath/save_journal_entry";
import { saveNotificationSettings as api_sabbath_save_notification_settings_saveNotificationSettings } from "~backend/sabbath/save_notification_settings";
import { savePreferences as api_sabbath_save_preferences_savePreferences } from "~backend/sabbath/save_preferences";
import { searchBibleVerses as api_sabbath_search_bible_verses_searchBibleVerses } from "~backend/sabbath/search_bible_verses";
import { getDailyReels as api_feed_get_daily_reels_getDailyReels } from "~backend/feed/get_daily_reels";
import { likeReel as api_feed_like_reel_likeReel } from "~backend/feed/like_reel";

export namespace sabbath {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createHymn = this.createHymn.bind(this)
            this.deleteBibleBookmark = this.deleteBibleBookmark.bind(this)
            this.deleteBibleVerseNote = this.deleteBibleVerseNote.bind(this)
            this.findChurches = this.findChurches.bind(this)
            this.getBibleBookmarks = this.getBibleBookmarks.bind(this)
            this.getBibleBooks = this.getBibleBooks.bind(this)
            this.getBibleChapter = this.getBibleChapter.bind(this)
            this.getBibleCommentary = this.getBibleCommentary.bind(this)
            this.getBibleCrossReferences = this.getBibleCrossReferences.bind(this)
            this.getBibleTranslations = this.getBibleTranslations.bind(this)
            this.getBibleVerse = this.getBibleVerse.bind(this)
            this.getBibleVerseNotes = this.getBibleVerseNotes.bind(this)
            this.getCurrentSabbathSchoolLesson = this.getCurrentSabbathSchoolLesson.bind(this)
            this.getDevotionals = this.getDevotionals.bind(this)
            this.getHymnById = this.getHymnById.bind(this)
            this.getHymnCategories = this.getHymnCategories.bind(this)
            this.getHymnThemes = this.getHymnThemes.bind(this)
            this.getHymns = this.getHymns.bind(this)
            this.getJournalEntries = this.getJournalEntries.bind(this)
            this.getNotificationSettings = this.getNotificationSettings.bind(this)
            this.getPendingNotifications = this.getPendingNotifications.bind(this)
            this.getPreferences = this.getPreferences.bind(this)
            this.getSabbathSchoolDailyStudies = this.getSabbathSchoolDailyStudies.bind(this)
            this.getSabbathSchoolLessons = this.getSabbathSchoolLessons.bind(this)
            this.getSabbathSchoolQuarters = this.getSabbathSchoolQuarters.bind(this)
            this.getSabbathTimes = this.getSabbathTimes.bind(this)
            this.saveBibleBookmark = this.saveBibleBookmark.bind(this)
            this.saveBibleVerseNote = this.saveBibleVerseNote.bind(this)
            this.saveJournalEntry = this.saveJournalEntry.bind(this)
            this.saveNotificationSettings = this.saveNotificationSettings.bind(this)
            this.savePreferences = this.savePreferences.bind(this)
            this.searchBibleVerses = this.searchBibleVerses.bind(this)
        }

        /**
         * Creates a new hymn
         */
        public async createHymn(params: RequestType<typeof api_sabbath_create_hymn_createHymn>): Promise<ResponseType<typeof api_sabbath_create_hymn_createHymn>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/hymns`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_create_hymn_createHymn>
        }

        /**
         * Deletes a Bible bookmark
         */
        public async deleteBibleBookmark(params: RequestType<typeof api_sabbath_delete_bible_bookmark_deleteBibleBookmark>): Promise<void> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            await this.baseClient.callTypedAPI(`/bible/bookmarks/${encodeURIComponent(params.bookmarkId)}`, {query, method: "DELETE", body: undefined})
        }

        /**
         * Deletes a Bible verse note
         */
        public async deleteBibleVerseNote(params: RequestType<typeof api_sabbath_delete_bible_verse_note_deleteBibleVerseNote>): Promise<void> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            await this.baseClient.callTypedAPI(`/bible/verse-notes/${encodeURIComponent(params.noteId)}`, {query, method: "DELETE", body: undefined})
        }

        /**
         * Finds SDA churches near a location
         */
        public async findChurches(params: RequestType<typeof api_sabbath_find_churches_findChurches>): Promise<ResponseType<typeof api_sabbath_find_churches_findChurches>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                latitude:  String(params.latitude),
                longitude: String(params.longitude),
                radius:    params.radius === undefined ? undefined : String(params.radius),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/churches/nearby`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_find_churches_findChurches>
        }

        /**
         * Retrieves Bible bookmarks for a user
         */
        public async getBibleBookmarks(params: RequestType<typeof api_sabbath_get_bible_bookmarks_getBibleBookmarks>): Promise<ResponseType<typeof api_sabbath_get_bible_bookmarks_getBibleBookmarks>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                tag: params.tag,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/bookmarks/${encodeURIComponent(params.userId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_bookmarks_getBibleBookmarks>
        }

        /**
         * Retrieves all Bible books
         */
        public async getBibleBooks(): Promise<ResponseType<typeof api_sabbath_get_bible_books_getBibleBooks>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/books`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_books_getBibleBooks>
        }

        /**
         * Retrieves all verses in a Bible chapter
         */
        public async getBibleChapter(params: RequestType<typeof api_sabbath_get_bible_chapter_getBibleChapter>): Promise<ResponseType<typeof api_sabbath_get_bible_chapter_getBibleChapter>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:        String(params.bookId),
                chapter:       String(params.chapter),
                translationId: params.translationId === undefined ? undefined : String(params.translationId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/chapter`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_chapter_getBibleChapter>
        }

        /**
         * Retrieves commentary for a specific Bible chapter or verse
         */
        public async getBibleCommentary(params: RequestType<typeof api_sabbath_get_bible_commentary_getBibleCommentary>): Promise<ResponseType<typeof api_sabbath_get_bible_commentary_getBibleCommentary>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:  String(params.bookId),
                chapter: String(params.chapter),
                verse:   params.verse === undefined ? undefined : String(params.verse),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/commentary`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_commentary_getBibleCommentary>
        }

        /**
         * Retrieves cross-references for a specific Bible verse
         */
        public async getBibleCrossReferences(params: RequestType<typeof api_sabbath_get_bible_cross_references_getBibleCrossReferences>): Promise<ResponseType<typeof api_sabbath_get_bible_cross_references_getBibleCrossReferences>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:  String(params.bookId),
                chapter: String(params.chapter),
                verse:   String(params.verse),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/cross-references`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_cross_references_getBibleCrossReferences>
        }

        /**
         * Retrieves all available Bible translations
         */
        public async getBibleTranslations(): Promise<ResponseType<typeof api_sabbath_get_bible_translations_getBibleTranslations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/translations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_translations_getBibleTranslations>
        }

        /**
         * Retrieves a specific Bible verse
         */
        public async getBibleVerse(params: RequestType<typeof api_sabbath_get_bible_verse_getBibleVerse>): Promise<ResponseType<typeof api_sabbath_get_bible_verse_getBibleVerse>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:        String(params.bookId),
                chapter:       String(params.chapter),
                translationId: params.translationId === undefined ? undefined : String(params.translationId),
                verse:         String(params.verse),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/verse`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_verse_getBibleVerse>
        }

        /**
         * Retrieves verse notes for a user, optionally filtered by book/chapter/verse
         */
        public async getBibleVerseNotes(params: RequestType<typeof api_sabbath_get_bible_verse_notes_getBibleVerseNotes>): Promise<ResponseType<typeof api_sabbath_get_bible_verse_notes_getBibleVerseNotes>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:  params.bookId === undefined ? undefined : String(params.bookId),
                chapter: params.chapter === undefined ? undefined : String(params.chapter),
                userId:  params.userId,
                verse:   params.verse === undefined ? undefined : String(params.verse),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/verse-notes`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_bible_verse_notes_getBibleVerseNotes>
        }

        /**
         * Retrieves the current week's Sabbath School lesson
         */
        public async getCurrentSabbathSchoolLesson(): Promise<ResponseType<typeof api_sabbath_get_current_sabbath_school_lesson_getCurrentSabbathSchoolLesson>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sabbath-school/current`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_current_sabbath_school_lesson_getCurrentSabbathSchoolLesson>
        }

        /**
         * Retrieves devotionals for offline use
         */
        public async getDevotionals(params: RequestType<typeof api_sabbath_get_devotionals_getDevotionals>): Promise<ResponseType<typeof api_sabbath_get_devotionals_getDevotionals>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category,
                date:     params.date,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/devotionals`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_devotionals_getDevotionals>
        }

        /**
         * Retrieves a specific hymn by ID
         */
        public async getHymnById(params: { id: number }): Promise<ResponseType<typeof api_sabbath_get_hymn_by_id_getHymnById>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/hymns/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_hymn_by_id_getHymnById>
        }

        /**
         * Retrieves all hymn categories with counts
         */
        public async getHymnCategories(): Promise<ResponseType<typeof api_sabbath_get_hymn_categories_getHymnCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/hymns/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_hymn_categories_getHymnCategories>
        }

        /**
         * Retrieves all hymn themes with counts
         */
        public async getHymnThemes(): Promise<ResponseType<typeof api_sabbath_get_hymn_themes_getHymnThemes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/hymns/themes`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_hymn_themes_getHymnThemes>
        }

        /**
         * Retrieves hymns with optional filtering and search
         */
        public async getHymns(params: RequestType<typeof api_sabbath_get_hymns_getHymns>): Promise<ResponseType<typeof api_sabbath_get_hymns_getHymns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category,
                limit:    params.limit === undefined ? undefined : String(params.limit),
                offset:   params.offset === undefined ? undefined : String(params.offset),
                search:   params.search,
                theme:    params.theme,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/hymns`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_hymns_getHymns>
        }

        /**
         * Retrieves journal entries for a user
         */
        public async getJournalEntries(params: RequestType<typeof api_sabbath_get_journal_entries_getJournalEntries>): Promise<ResponseType<typeof api_sabbath_get_journal_entries_getJournalEntries>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                endDate:   params.endDate,
                startDate: params.startDate,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal/${encodeURIComponent(params.userId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_journal_entries_getJournalEntries>
        }

        /**
         * Retrieves notification settings for a user
         */
        public async getNotificationSettings(params: { userId: string }): Promise<ResponseType<typeof api_sabbath_get_notification_settings_getNotificationSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/settings/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_notification_settings_getNotificationSettings>
        }

        /**
         * Retrieves pending notifications for a user based on their location and Sabbath times
         */
        public async getPendingNotifications(params: RequestType<typeof api_sabbath_get_pending_notifications_getPendingNotifications>): Promise<ResponseType<typeof api_sabbath_get_pending_notifications_getPendingNotifications>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                latitude:  String(params.latitude),
                longitude: String(params.longitude),
                userId:    params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/pending`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_pending_notifications_getPendingNotifications>
        }

        /**
         * Retrieves user preferences
         */
        public async getPreferences(params: { userId: string }): Promise<ResponseType<typeof api_sabbath_get_preferences_getPreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/preferences/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_preferences_getPreferences>
        }

        /**
         * Retrieves daily studies for a specific lesson
         */
        public async getSabbathSchoolDailyStudies(params: { lessonId: number }): Promise<ResponseType<typeof api_sabbath_get_sabbath_school_daily_studies_getSabbathSchoolDailyStudies>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sabbath-school/lessons/${encodeURIComponent(params.lessonId)}/daily-studies`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_sabbath_school_daily_studies_getSabbathSchoolDailyStudies>
        }

        /**
         * Retrieves lessons for a specific quarter
         */
        public async getSabbathSchoolLessons(params: { quarterId: number }): Promise<ResponseType<typeof api_sabbath_get_sabbath_school_lessons_getSabbathSchoolLessons>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sabbath-school/quarters/${encodeURIComponent(params.quarterId)}/lessons`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_sabbath_school_lessons_getSabbathSchoolLessons>
        }

        /**
         * Retrieves all Sabbath School quarters
         */
        public async getSabbathSchoolQuarters(): Promise<ResponseType<typeof api_sabbath_get_sabbath_school_quarters_getSabbathSchoolQuarters>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sabbath-school/quarters`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_sabbath_school_quarters_getSabbathSchoolQuarters>
        }

        /**
         * Calculates Sabbath start and end times based on location
         */
        public async getSabbathTimes(params: RequestType<typeof api_sabbath_get_sabbath_times_getSabbathTimes>): Promise<ResponseType<typeof api_sabbath_get_sabbath_times_getSabbathTimes>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                latitude:  String(params.latitude),
                longitude: String(params.longitude),
                timezone:  params.timezone,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sabbath/times`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_get_sabbath_times_getSabbathTimes>
        }

        /**
         * Saves or updates a Bible bookmark
         */
        public async saveBibleBookmark(params: RequestType<typeof api_sabbath_save_bible_bookmark_saveBibleBookmark>): Promise<ResponseType<typeof api_sabbath_save_bible_bookmark_saveBibleBookmark>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/bookmarks`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_save_bible_bookmark_saveBibleBookmark>
        }

        /**
         * Saves or updates a verse note/highlight
         */
        public async saveBibleVerseNote(params: RequestType<typeof api_sabbath_save_bible_verse_note_saveBibleVerseNote>): Promise<ResponseType<typeof api_sabbath_save_bible_verse_note_saveBibleVerseNote>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/verse-notes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_save_bible_verse_note_saveBibleVerseNote>
        }

        /**
         * Saves a journal entry for reflection
         */
        public async saveJournalEntry(params: RequestType<typeof api_sabbath_save_journal_entry_saveJournalEntry>): Promise<ResponseType<typeof api_sabbath_save_journal_entry_saveJournalEntry>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/journal`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_save_journal_entry_saveJournalEntry>
        }

        /**
         * Saves notification settings for a user
         */
        public async saveNotificationSettings(params: RequestType<typeof api_sabbath_save_notification_settings_saveNotificationSettings>): Promise<ResponseType<typeof api_sabbath_save_notification_settings_saveNotificationSettings>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/settings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_save_notification_settings_saveNotificationSettings>
        }

        /**
         * Saves user preferences for Sabbath preparation
         */
        public async savePreferences(params: RequestType<typeof api_sabbath_save_preferences_savePreferences>): Promise<ResponseType<typeof api_sabbath_save_preferences_savePreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/preferences`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_save_preferences_savePreferences>
        }

        /**
         * Searches Bible verses by text content using PostgreSQL full-text search
         */
        public async searchBibleVerses(params: RequestType<typeof api_sabbath_search_bible_verses_searchBibleVerses>): Promise<ResponseType<typeof api_sabbath_search_bible_verses_searchBibleVerses>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bookId:        params.bookId === undefined ? undefined : String(params.bookId),
                limit:         params.limit === undefined ? undefined : String(params.limit),
                offset:        params.offset === undefined ? undefined : String(params.offset),
                query:         params.query,
                searchType:    params.searchType === undefined ? undefined : String(params.searchType),
                testament:     params.testament,
                translationId: params.translationId === undefined ? undefined : String(params.translationId),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/bible/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_sabbath_search_bible_verses_searchBibleVerses>
        }
    }
}

export namespace feed {
    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDailyReels = this.getDailyReels.bind(this)
            this.likeReel = this.likeReel.bind(this)
        }

        /**
         * Retrieves daily reels feed with optional pillar filter and pagination
         */
        public async getDailyReels(params: RequestType<typeof api_feed_get_daily_reels_getDailyReels>): Promise<ResponseType<typeof api_feed_get_daily_reels_getDailyReels>> {
            const query = makeRecord<string, string | string[]>({
                pillar: params.pillar,
                featuredOnly: params.featuredOnly === undefined ? undefined : String(params.featuredOnly),
                limit: params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            const resp = await this.baseClient.callTypedAPI(`/feed/reels`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_feed_get_daily_reels_getDailyReels>
        }

        /**
         * Atomically increments like counter for a reel
         */
        public async likeReel(params: RequestType<typeof api_feed_like_reel_likeReel>): Promise<ResponseType<typeof api_feed_like_reel_likeReel>> {
            const resp = await this.baseClient.callTypedAPI(`/feed/reels/${encodeURIComponent(params.id)}/like`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_feed_like_reel_likeReel>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
